### ISSUE TITLE
add github logo to footer

### ISSUE THREAD

**Issue by AmirNaghibi** [sfusurge/z-archived-sfusurge.github.io.v1#2]
update HTML (https://www.sfusurge.com/) to add the GitHub logo to the footer for all the pages.

link the GitHub logo to SFU surge GitHub (https://github.com/sfusurge)

**Comment by plaidshirtakos** [comment]
I just added it: https://github.com/sfusurge/sfusurge.github.io/pull/3

**Comment by AmirNaghibi** [comment]
Thanks! The PR has been merged and deployed!
