### ISSUE TITLE
Center the div element for each event

### ISSUE THREAD

**Issue by AmirNaghibi** [sfusurge/z-archived-sfusurge.github.io.v1#21]
each event card is a div spanning the entire width of the page. 

**Center the div element.** The associated css is /assets/css/mainpage.css

<img width="1004" alt="Screen Shot 2019-10-19 at 6 36 35 PM" src="https://user-images.githubusercontent.com/20001191/67153536-f4a9c780-f29f-11e9-9e15-b8db280e4c6e.png">

**Make sure it scales in mobile too**

<img width="271" alt="Screen Shot 2019-10-19 at 6 35 24 PM" src="https://user-images.githubusercontent.com/20001191/67153542-04c1a700-f2a0-11e9-92ad-87cc3941480b.png">

**Comment by justinlyan** [comment]
I would like to work on this issue.
